WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
WINDOW_SIZE = (WINDOW_WIDTH, WINDOW_HEIGHT)

WINDOW_TITLE = "校徽合成"
FPS = 60

NUMBER_PATH = "assets/images/number.png"
BADGE_PATH = "asssets/images/badge.png"

SYNTHESIS_SOUND_PATH = "assets/sounds/synthesis.mp3"
SPEEDUP_SOUND_PATH = "assets/sounds/speedup.mp3"
COLLIDE_SOUND_PATH = "assets/sounds/collide.mp3"

VERTICAL_SPEEDUP = 5

GRAVITY = 1500

DEFAULT_DAMPING = 1.0
PLAYER_DAMPING = 0.4

PLYAYER_FRICITON = 1
PLATFORM_FRICTION = 0.7
DYNAMIC_ITEMS_FRICTION = 0.6

PLAYER_MASS = 2.0
PLAYER_MAX_VERTICAL_SPEED = 1000
PLAYER_MAX_HORIZONTAL_SPEED = 450