WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
WINDOW_SIZE = (WINDOW_WIDTH, WINDOW_HEIGHT)

WINDOW_TITLE = "校徽合成"
FPS = 60

NUMBER_PATH = "assets/images/number.png"
BADGE_PATH = "assets/images/badge.png"
PLATFORM_PATH = ":resources:images/tiles/dirtHalf.png"

SYNTHESIS_SOUND_PATH = "assets/sounds/synthesis.mp3"
SPEEDUP_SOUND_PATH = "assets/sounds/speedup.mp3"
COLLIDE_SOUND_PATH = "assets/sounds/collide.mp3"

PLATFORM_SCALE = 0.5
PLATFORM_HEIGHT = 0

VERTICAL_SPEEDUP = 20

GRAVITY = 1500

DEFAULT_DAMPING = 1.0
PLAYER_DAMPING = 0.4

PLYAYER_FRICITON = 1.0
PLATFORM_FRICTION = 0.7
DYNAMIC_ITEMS_FRICTION = 0.6

PLAYER_MASS = 2.0
MAX_VERTICAL_SPEED = -50
MAX_HORIZONTAL_SPEED = 40